# Configuration properties for OrangeHRM Automation
base.url=https://opensource-demo.orangehrmlive.com
browser=chrome
headless=false
explicit.wait=15

# Default credentials for OrangeHRM Demo
default.username=Admin
default.password=admin123
